alias vim="/usr/local/Cellar/vim/7.4.2109/bin/vim"
alias g='grep -rin --color=auto --exclude-dir=\*.git\* --exclude=\*.min.\* --exclude-dir=\*ckeditor/lang\* --exclude-dir=\*db/data\* --exclude=\*.log --exclude-dir=\*tmp\/cache\* --exclude-dir=\*coverage\* --exclude-dir=\*public/assets\* --exclude-dir=\*node_modules\* --exclude-dir=\*app/assets/webpack\* --exclude=tags --exclude-dir=\*db/views\*'
alias gl='grep -rin --color=auto --exclude-dir=\*.git\* --exclude=\*.min.\* --exclude-dir=\*ckeditor/lang\*'
alias gcase='grep -rn --exclude-dir=\*.git\* --exclude=\*.min.\* --exclude-dir=\*ckeditor/lang\*'
alias rdb='vim ~/pf3/public/javascripts/v3/readability.js'
alias b='bundle exec'
alias rme='vim ~/.vim/gagienv/readmeruby.txt'
alias pfd='vim ~/Desktop/pfdata.txt'
alias ll='ls -al'
alias llt='ls -lat'
alias l.='ls -lAdF ${H} ${LS_COLOUR} .*'
alias rs='rails s -b 10.0.0.100'
alias zz='tar -zcvf $1 $2'
alias az='vim ~/.bash_aliases'
alias dj='b rake jobs:work'
alias mem='gnome-system-monitor'
alias canvas='export SCRIPT_SERVER_NO_GUARD=1 && b script/server'
alias cdac='cd ~/dev/src/rdesktop/Client/AndroidClient'
alias rdesk='cd ~/dev/src/rdesktop'
alias cdndk='cd ~/dev/sdk/android-ndk-r8e/'
alias vnc='cd ~/Downloads && setsid ./VNC-Viewer-5.0.5-Linux-x86'
alias cpan='cd ~/dev/src/cpanel'
alias frame='cd ~/dev/src/frame'
alias hh='cd ~/dev/src/health'
alias fb='cd ~/dev/src/facebook-hacker-cup-2017/'
alias kata='cd ~/dev/src/kata/'
alias ana='cd ~/dev/src/ana/'
alias thc='cd ~/dev/src/thc'
alias dvv='cd ~/dev/src/dvvdb'
alias rundvv='dvv && foreman start'
alias disp='cd ~/dev/src/dispatcher'
alias lay='vim app/views/layouts/application.html.erb'
#alias rundj='disp && cd djapp && python manage.py runserver'
alias rundj='disp && cd djapp && python manage.py runfcgi method=threaded host=127.0.0.1 port=3033'
alias resdj='kill -7 `ps ax | grep fcgi | head -n 1 | awk '\''{ print \$1}'\''` && rundj'
alias tes='ps ax | grep fcgi | head -n 1 | awk "{ print \$1}"'
#alias runr='export RACK_ENV=development && cpan && guard >/dev/null 2>&1 & foreman start'
alias ct='ctags --tag-relative -R --sort=yes --languages=ruby,javascript --exclude=.git --exclude=log . $(bundle list --paths)'
alias runr='export RACK_ENV=development && cpan && foreman start all=1,mqworker=2'
alias rmpid='rmfile /usr/local/var/postgres/postmaster.pid'
alias runp='export RACK_ENV=production && cpan && foreman start all=1,mqworker=2'
alias runrp='export RACK_ENV=profile && cpan && foreman start'
alias runrpm='export RACK_ENV=profile && export RUBY_PROF_MEASURE_MODE=allocations && cpan && foreman start'
alias cdgems='cd ~/.rvm/gems/ruby-2.3.4@mf2/gems'
alias dropbox='~/.dropbox-dist/dropboxd &'
alias rlog='tail -n 101 log/development.log'
alias rswp='find . -name \*.swp -type f -delete && find . -name \*.orig -type f -delete'
alias glist1='for ref in $(git for-each-ref --sort=-committerdate --format="%(refname)" refs/heads/ refs/remotes ); do git log -n1 $ref --pretty=format:"%Cgreen%cr%Creset %C(yellow)%d%Creset %C(bold blue)<%an>%Creset%n" | cat ; done | awk '"'! a["'$0'"]++'"
alias fh='ffc home'
