alias g='grep -rin --exclude-dir=\*.git\* --exclude=\*.min.\* --exclude-dir=\*ckeditor/lang\*'
alias gcase='grep -rn --exclude-dir=\*.git\* --exclude=\*.min.\* --exclude-dir=\*ckeditor/lang\*'
alias rdb='gvim ~/pf3/public/javascripts/v3/readability.js'
alias pf='gvim ~/pf3/public/printfriendly.js'
alias pf4='gvim ~/pf3/public/javascripts/v4/printfriendly.js'
alias pf5='gvim ~/pf3/public/javascripts/v5/printfriendly.js'
alias b='bundle exec'
alias rme='gvim ~/.vim/gagienv/readmeruby.txt'
alias pfd='gvim ~/Desktop/pfdata.txt'
alias llt='ls -lat'
alias l.='ls -lAdF ${H} ${LS_COLOUR} .*'
alias rs='rails s -b 10.0.0.100'
alias zz='tar -zcvf $1 $2'
alias az='gvim ~/.bash_aliases'
alias dj='b rake jobs:work'
alias mem='gnome-system-monitor'
alias wppf='scp -r ~/wpgit/pf.php htz:/var/www/phptest/wordpress-3-5-1/wp-content/plugins/printfriendly/'
alias wppfall='scp -r ~/wpgit/* htz:/var/www/phptest/wordpress-3-5-1/wp-content/plugins/printfriendly/'
alias wppfall28='scp -r ~/wpgit/* htz:/var/www/phptest/wordpress-2-8/wp-content/plugins/printfriendly/'
alias wppfall29='scp -r ~/wpgit/* htz:/var/www/phptest/wordpress-2-9/wp-content/plugins/printfriendly/'
alias wppfs='wppf;scp -r ~/wpgit/admin.js htz:/var/www/phptest/wordpress-3-5-1/wp-content/plugins/printfriendly/'
alias svnpf='cp -r ~/wpgit/* ~/pfwp/printfriendly/trunk/'
alias wpemail='scp -r ~/instaemail/instaemail.php htz:/var/www/phptest/wordpress-3-5-1/wp-content/plugins/email-this-page/'
alias wpemailall='scp -r ~/instaemail/* htz:/var/www/phptest/wordpress-3-5-1/wp-content/plugins/email-this-page/'
alias svnemail='cp -r ~/instaemail/* ~/email-this-page/trunk'
alias drupdate='scp -r ~/pfdrupal/* htz:/var/www/phptest/drupal-7-19/sites/all/modules/printfriendly/'
alias wptry='scp -r ~/snipets/wptry.php htz:/var/www/p3stats/public/php/wordpress-3-5-1/'
alias wpemailtranslate='php ~/wputils/trunk/makepot.php wp-plugin ~/instaemail ~/instaemail/languages/instaemail.pot'
alias pf3https='thin start --ssl --ssl-verify --ssl-key-file /home/ubuntu/ssl-stuff/local-printfriendly.cert.key --ssl-cert-file /home/ubuntu/ssl-stuff/pflocal.crt -p 3001'
alias wpcustom='scp ~/pfads/bloggottabuys.php htz:/var/www/phptest/wordpress-3-5-1/wp-content/themes/twentytwelve/'
alias canvas='export SCRIPT_SERVER_NO_GUARD=1 && b script/server'
alias cdac='cd ~/dev/src/rdesktop/Client/AndroidClient'
alias rdesk='cd ~/dev/src/rdesktop'
alias cdndk='cd ~/dev/sdk/android-ndk-r8e/'
alias vnc='cd ~/Downloads && setsid ./VNC-Viewer-5.0.5-Linux-x86'
alias cpan='cd ~/dev/src/cpanel'
alias dvv='cd ~/dev/src/dvvdb'
alias rundvv='dvv && foreman start'
alias disp='cd ~/dev/src/dispatcher'
alias lay='gvim app/views/layouts/application.html.erb'
#alias rundj='disp && cd djapp && python manage.py runserver'
alias rundj='disp && cd djapp && python manage.py runfcgi method=threaded host=127.0.0.1 port=3033'
alias resdj='kill -7 `ps ax | grep fcgi | head -n 1 | awk '\''{ print \$1}'\''` && rundj'
alias tes='ps ax | grep fcgi | head -n 1 | awk "{ print \$1}"'
alias runr='export RACK_ENV=development && cpan && foreman start'
alias runrp='export RACK_ENV=profile && cpan && foreman start'
alias cdgems='cd ~/.rvm/gems/ruby-2.0.0-p195@mf2/gems'
alias dropbox='~/.dropbox-dist/dropboxd &'
alias rlog='tail -n 101 log/development.log'
alias rswp='find . -name \*.swp -type f -delete'
